# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 28.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gitea_api.models.create_deploy_key_token_option import CreateDeployKeyTokenOption

class TestCreateDeployKeyTokenOption(unittest.TestCase):
    """CreateDeployKeyTokenOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateDeployKeyTokenOption:
        """Test CreateDeployKeyTokenOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateDeployKeyTokenOption`
        """
        model = CreateDeployKeyTokenOption()
        if include_optional:
            return CreateDeployKeyTokenOption(
                read_only = True,
                title = ''
            )
        else:
            return CreateDeployKeyTokenOption(
                title = '',
        )
        """

    def testCreateDeployKeyTokenOption(self):
        """Test CreateDeployKeyTokenOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
