# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 28.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gitea_api.models.move_project_columns_option import MoveProjectColumnsOption

class TestMoveProjectColumnsOption(unittest.TestCase):
    """MoveProjectColumnsOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MoveProjectColumnsOption:
        """Test MoveProjectColumnsOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MoveProjectColumnsOption`
        """
        model = MoveProjectColumnsOption()
        if include_optional:
            return MoveProjectColumnsOption(
                column_ids = [
                    56
                    ]
            )
        else:
            return MoveProjectColumnsOption(
                column_ids = [
                    56
                    ],
        )
        """

    def testMoveProjectColumnsOption(self):
        """Test MoveProjectColumnsOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
