# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.27.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gitea_api.models.pull_request_minimal import PullRequestMinimal

class TestPullRequestMinimal(unittest.TestCase):
    """PullRequestMinimal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PullRequestMinimal:
        """Test PullRequestMinimal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PullRequestMinimal`
        """
        model = PullRequestMinimal()
        if include_optional:
            return PullRequestMinimal(
                base = gitea_api.models.pull_request_minimal_head_is_a_minimal_description_of_one_side_of_a_pull_request/.PullRequestMinimalHead is a minimal description of one side of a pull request.(
                    ref = '', 
                    repo = gitea_api.models.pull_request_minimal_head_repo_is_a_minimal_description_of_the_repository_on_one_side_of_a_pull_request/.PullRequestMinimalHeadRepo is a minimal description of the repository on one side of a pull request.(
                        id = 56, 
                        name = '', 
                        url = '', ), 
                    sha = '', ),
                head = gitea_api.models.pull_request_minimal_head_is_a_minimal_description_of_one_side_of_a_pull_request/.PullRequestMinimalHead is a minimal description of one side of a pull request.(
                    ref = '', 
                    repo = gitea_api.models.pull_request_minimal_head_repo_is_a_minimal_description_of_the_repository_on_one_side_of_a_pull_request/.PullRequestMinimalHeadRepo is a minimal description of the repository on one side of a pull request.(
                        id = 56, 
                        name = '', 
                        url = '', ), 
                    sha = '', ),
                id = 56,
                number = 56,
                url = ''
            )
        else:
            return PullRequestMinimal(
        )
        """

    def testPullRequestMinimal(self):
        """Test PullRequestMinimal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
