# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.24.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gitea_api.api.package_api import PackageApi


class TestPackageApi(unittest.TestCase):
    """PackageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PackageApi()

    def tearDown(self) -> None:
        pass

    def test_delete_package(self) -> None:
        """Test case for delete_package

        Delete a package
        """
        pass

    def test_get_latest_package_version(self) -> None:
        """Test case for get_latest_package_version

        Gets the latest version of a package
        """
        pass

    def test_get_package(self) -> None:
        """Test case for get_package

        Gets a package
        """
        pass

    def test_link_package(self) -> None:
        """Test case for link_package

        Link a package to a repository
        """
        pass

    def test_list_package_files(self) -> None:
        """Test case for list_package_files

        Gets all files of a package
        """
        pass

    def test_list_package_versions(self) -> None:
        """Test case for list_package_versions

        Gets all versions of a package
        """
        pass

    def test_list_packages(self) -> None:
        """Test case for list_packages

        Gets all packages of an owner
        """
        pass

    def test_unlink_package(self) -> None:
        """Test case for unlink_package

        Unlink a package from a repository
        """
        pass


if __name__ == '__main__':
    unittest.main()
