# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.23.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_gitea_opensuse_org.api.package_api import PackageApi


class TestPackageApi(unittest.IsolatedAsyncioTestCase):
    """PackageApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PackageApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_package(self) -> None:
        """Test case for delete_package

        Delete a package
        """
        pass

    async def test_get_package(self) -> None:
        """Test case for get_package

        Gets a package
        """
        pass

    async def test_list_package_files(self) -> None:
        """Test case for list_package_files

        Gets all files of a package
        """
        pass

    async def test_list_packages(self) -> None:
        """Test case for list_packages

        Gets all packages of an owner
        """
        pass


if __name__ == '__main__':
    unittest.main()
