# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.24.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gitea_api.models.contents_response import ContentsResponse

class TestContentsResponse(unittest.TestCase):
    """ContentsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentsResponse:
        """Test ContentsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentsResponse`
        """
        model = ContentsResponse()
        if include_optional:
            return ContentsResponse(
                links = gitea_api.models.file_links_response.FileLinksResponse(
                    git = '', 
                    html = '', 
                    self = '', ),
                content = '',
                download_url = '',
                encoding = '',
                git_url = '',
                html_url = '',
                last_author_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_commit_sha = '',
                last_committer_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                path = '',
                sha = '',
                size = 56,
                submodule_git_url = '',
                target = '',
                type = '',
                url = ''
            )
        else:
            return ContentsResponse(
        )
        """

    def testContentsResponse(self):
        """Test ContentsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
