# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.27.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gitea_api.models.current_access_token import CurrentAccessToken

class TestCurrentAccessToken(unittest.TestCase):
    """CurrentAccessToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrentAccessToken:
        """Test CurrentAccessToken
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurrentAccessToken`
        """
        model = CurrentAccessToken()
        if include_optional:
            return CurrentAccessToken(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = 56,
                last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                scopes = [
                    ''
                    ],
                user = gitea_api.models.user_meta_represents_minimal_user_information_for_the_token_owner/.UserMeta represents minimal user information for the token owner.(
                    id = 56, 
                    login = '', )
            )
        else:
            return CurrentAccessToken(
        )
        """

    def testCurrentAccessToken(self):
        """Test CurrentAccessToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
