# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.23.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_gitea_opensuse_org.api.settings_api import SettingsApi


class TestSettingsApi(unittest.IsolatedAsyncioTestCase):
    """SettingsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SettingsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_general_api_settings(self) -> None:
        """Test case for get_general_api_settings

        Get instance's global settings for api
        """
        pass

    async def test_get_general_attachment_settings(self) -> None:
        """Test case for get_general_attachment_settings

        Get instance's global settings for Attachment
        """
        pass

    async def test_get_general_repository_settings(self) -> None:
        """Test case for get_general_repository_settings

        Get instance's global settings for repositories
        """
        pass

    async def test_get_general_ui_settings(self) -> None:
        """Test case for get_general_ui_settings

        Get instance's global settings for ui
        """
        pass


if __name__ == '__main__':
    unittest.main()
