# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 28.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from gitea_api.models.user import User
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Project(BaseModel):
    """
    Projects track issues and pull requests, standalone note cards are not supported.
    """ # noqa: E501
    card_type: Optional[StrictStr] = Field(default=None, description="Card type: \"text_only\" or \"images_and_text\"")
    closed_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    creator: Optional[User] = None
    creator_id: Optional[StrictInt] = Field(default=None, description="Deprecated: use Creator instead")
    description: Optional[StrictStr] = None
    html_url: Optional[StrictStr] = None
    id: Optional[StrictInt] = None
    is_closed: Optional[StrictBool] = Field(default=None, description="Deprecated: use State instead")
    num_closed_issues: Optional[StrictInt] = None
    num_issues: Optional[StrictInt] = None
    num_open_issues: Optional[StrictInt] = None
    owner_id: Optional[StrictInt] = None
    repo_id: Optional[StrictInt] = None
    state: Optional[StrictStr] = None
    template_type: Optional[StrictStr] = Field(default=None, description="Template type: \"none\", \"basic_kanban\" or \"bug_triage\"")
    title: Optional[StrictStr] = None
    type: Optional[StrictStr] = Field(default=None, description="Project type: \"individual\", \"repository\" or \"organization\"")
    updated_at: Optional[datetime] = Field(default=None, description="null only for legacy rows that carry no update timestamp")
    __properties: ClassVar[List[str]] = ["card_type", "closed_at", "created_at", "creator", "creator_id", "description", "html_url", "id", "is_closed", "num_closed_issues", "num_issues", "num_open_issues", "owner_id", "repo_id", "state", "template_type", "title", "type", "updated_at"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['open', 'closed']):
            raise ValueError("must be one of enum values ('open', 'closed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Project from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of creator
        if self.creator:
            _dict['creator'] = self.creator.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Project from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "card_type": obj.get("card_type"),
            "closed_at": obj.get("closed_at"),
            "created_at": obj.get("created_at"),
            "creator": User.from_dict(obj["creator"]) if obj.get("creator") is not None else None,
            "creator_id": obj.get("creator_id"),
            "description": obj.get("description"),
            "html_url": obj.get("html_url"),
            "id": obj.get("id"),
            "is_closed": obj.get("is_closed"),
            "num_closed_issues": obj.get("num_closed_issues"),
            "num_issues": obj.get("num_issues"),
            "num_open_issues": obj.get("num_open_issues"),
            "owner_id": obj.get("owner_id"),
            "repo_id": obj.get("repo_id"),
            "state": obj.get("state"),
            "template_type": obj.get("template_type"),
            "title": obj.get("title"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


