# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.27.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Project(BaseModel):
    """
    Project represents a project
    """ # noqa: E501
    closed_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    creator_id: Optional[StrictInt] = Field(default=None, description="CreatorID is the user who created the project")
    description: Optional[StrictStr] = Field(default=None, description="Description provides details about the project")
    id: Optional[StrictInt] = Field(default=None, description="ID is the unique identifier for the project")
    is_closed: Optional[StrictBool] = Field(default=None, description="IsClosed indicates if the project is closed")
    owner_id: Optional[StrictInt] = Field(default=None, description="OwnerID is the owner of the project (for org-level projects)")
    repo_id: Optional[StrictInt] = Field(default=None, description="RepoID is the repository this project belongs to (for repo-level projects)")
    title: Optional[StrictStr] = Field(default=None, description="Title is the title of the project")
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["closed_at", "created_at", "creator_id", "description", "id", "is_closed", "owner_id", "repo_id", "title", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Project from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Project from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "closed_at": obj.get("closed_at"),
            "created_at": obj.get("created_at"),
            "creator_id": obj.get("creator_id"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "is_closed": obj.get("is_closed"),
            "owner_id": obj.get("owner_id"),
            "repo_id": obj.get("repo_id"),
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


