# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.27.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gitea_api.models.pull_request_minimal_head import PullRequestMinimalHead
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PullRequestMinimal(BaseModel):
    """
    PullRequestMinimal is the minimal information about a pull request, as returned in the `pull_requests` field of a workflow run.
    """ # noqa: E501
    base: Optional[PullRequestMinimalHead] = None
    head: Optional[PullRequestMinimalHead] = None
    id: Optional[StrictInt] = None
    number: Optional[StrictInt] = None
    url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["base", "head", "id", "number", "url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PullRequestMinimal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base
        if self.base:
            _dict['base'] = self.base.to_dict()
        # override the default output from pydantic by calling `to_dict()` of head
        if self.head:
            _dict['head'] = self.head.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PullRequestMinimal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "base": PullRequestMinimalHead.from_dict(obj["base"]) if obj.get("base") is not None else None,
            "head": PullRequestMinimalHead.from_dict(obj["head"]) if obj.get("head") is not None else None,
            "id": obj.get("id"),
            "number": obj.get("number"),
            "url": obj.get("url")
        })
        return _obj


